### ISSUE TITLE
Error in Simple App's classes.dex file

### ISSUE THREAD

**Issue by adapana** [huuck/Katalina#1]
I created a sample app without using multi dex and then extracted classes.dex file and run Katalina, but this error shows.

ERROR    ←[35mError running La0/d;->onCreate: module 'signal' has no attribute 'SIGALRM'←[0m
ERROR    ←[35mError running Landroidx/activity/ComponentActivity;->onCreate: module 'signal' has no attribute 'SIGALRM'←[0m
ERROR    ←[35mError running Landroidx/appcompat/app/a;->onCreate: module 'signal' has no attribute 'SIGALRM'←[0m
ERROR    ←[35mError running Landroidx/appcompat/widget/AppCompatTextView;->onCreateInputConnection: module 'signal' has no attribute 'SIGALRM'←[0m
ERROR    ←[35mError running Landroidx/appcompat/widget/SearchView$SearchAutoComplete;->onCreateInputConnection: module 'signal' has no attribute 'SIGALRM'←[0m
ERROR    ←[35mError running Landroidx/appcompat/widget/d;->onCreateInputConnection: module 'signal' has no attribute 'SIGALRM'←[0m
ERROR    ←[35mError running Landroidx/appcompat/widget/h;->onCreateInputConnection: module 'signal' has no attribute 'SIGALRM'←[0m
ERROR    ←[35mError running Landroidx/appcompat/widget/k;->onCreateInputConnection: module 'signal' has no attribute 'SIGALRM'←[0m
ERROR    ←[35mError running Landroidx/appcompat/widget/p;->onCreateInputConnection: module 'signal' has no attribute 'SIGALRM'←[0m
ERROR    ←[35mError running Landroidx/core/content/FileProvider;->onCreate: module 'signal' has no attribute 'SIGALRM'←[0m
ERROR    ←[35mError running Landroidx/fragment/app/Fragment;->onCreateContextMenu: module 'signal' has no attribute 'SIGALRM'←[0m
ERROR    ←[35mError running Landroidx/fragment/app/g;->onCreateView: module 'signal' has no attribute 'SIGALRM'←[0m
ERROR    ←[35mError running Landroidx/fragment/app/g;->onCreateView: module 'signal' has no attribute 'SIGALRM'←[0m
ERROR    ←[35mError running Lcom/google/android/material/appbar/AppBarLayout;->onCreateDrawableState: module 'signal' has no attribute 'SIGALRM'←[0m
ERROR    ←[35mError running Lcom/google/android/material/button/MaterialButton;->onCreateDrawableState: module 'signal' has no attribute 'SIGALRM'←[0m
ERROR    ←[35mError running Lcom/google/android/material/chip/Chip;->onCreateDrawableState: module 'signal' has no attribute 'SIGALRM'←[0m
ERROR    ←[35mError running Lcom/google/android/material/internal/CheckableImageButton;->onCreateDrawableState: module 'signal' has no attribute 'SIGALRM'←[0m
ERROR    ←[35mError running Lcom/google/android/material/internal/NavigationMenuItemView;->onCreateDrawableState: module 'signal' has no attribute 'SIGALRM'←[0m
ERROR    ←[35mError running Lcom/google/android/material/textfield/TextInputEditText;->onCreateInputConnection: module 'signal' has no attribute 'SIGALRM'←[0m
ERROR    ←[35mError running Lcom/photovideomaker/MainClas;->onCreate: module 'signal' has no attribute 'SIGALRM'←[0m
ERROR    ←[35mError running Lcom/photovideomaker/SomeApp;->onCreate: module 'signal' has no attribute 'SIGALRM'←[0m

**Comment by huuck** [comment]
What OS are you running it on?

**Comment by adapana** [comment]
Windows 10

**Comment by huuck** [comment]
Please use Linux/WSL with all requirements installed, Windows is not supported for now.
